services:
  postgres:
    image: postgres
    restart: on-failure
    env_file:
      - server/.env
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    ports:
      - 3001:3001
    networks:
      - postgres
    depends_on:
      - postgres

  frontend:
    build:
      context: ./client
      dockerfile: client.Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

networks:
  postgres:
    driver: bridge